package conio

const CTRL_CLOSE_EVENT = 2
const CTRL_LOGOFF_EVENT = 5
const CTRL_SHUTDOWN_EVENT = 6
const CTRL_C_EVENT = 0
const ENABLE_ECHO_INPUT = 4
const ENABLE_PROCESSED_INPUT = 1
const STD_INPUT_HANDLE = uint32(0xFFFFFFF6)
const STD_OUTPUT_HANDLE = uint32(0xFFFFFFF5)
