go-importconst conio ^
    CTRL_CLOSE_EVENT ^
    CTRL_LOGOFF_EVENT ^
    CTRL_SHUTDOWN_EVENT ^
    CTRL_C_EVENT ^
    ENABLE_ECHO_INPUT ^
    ENABLE_PROCESSED_INPUT ^
    STD_INPUT_HANDLE:uint32:0x%%X ^
    STD_OUTPUT_HANDLE:uint32:0x%%X
