package lua

const LUA_REGISTRYINDEX = -1001000
const LUA_TBOOLEAN = 1
const LUA_TFUNCTION = 6
const LUA_TLIGHTUSERDATA = 2
const LUA_TNIL = 0
const LUA_TNUMBER = 3
const LUA_TSTRING = 4
const LUA_TTABLE = 5
const LUA_TTHREAD = 8
const LUA_TUSERDATA = 7
