package nodos

//go:generate go run ../dos/importconst_run.go COINIT_APARTMENTTHREADED COINIT_MULTITHREADED COINIT_DISABLE_OLE1DDE COINIT_SPEED_OVER_MEMORY FSCTL_SET_REPARSE_POINT WM_SETICON WM_GETICON ICON_BIG ICON_SMALL
