package functions

var Table = map[string]func(*Param) []interface{}{
	"box":                CmdBox,
	"raweval":            CmdRawEval,
	"rawexec":            CmdRawExec,
	"write":              CmdWrite,
	"writerr":            CmdWriteErr,
	"default_prompt":     Prompt,
	"access":             CmdAccess,
	"atou":               CmdAtoU,
	"atou_if_needed":     CmdAnsiToUtf8IfNeeded,
	"bitand":             CmdBitAnd,
	"bitor":              CmdBitOr,
	"chdir":              CmdChdir,
	"commonprefix":       CmdCommonPrefix,
	"complete_for_files": CmdCompleteForFiles,
	"dirname":            CmdDirName,
	"elevated":           CmdElevated,
	"envadd":             CmdEnvAdd,
	"envdel":             CmdEnvDel,
	"fields":             CmdFields,
	"getenv":             CmdGetEnv,
	"gethistory":         CmdGetHistory,
	"getkey":             CmdGetKey,
	"getkeys":            CmdGetKeys,
	"getviewwidth":       CmdGetViewWidth,
	"getwd":              CmdGetwd,
	"glob":               CmdGlob,
	"pathjoin":           CmdPathJoin,
	"setenv":             CmdSetEnv,
	"setnextline":        CmdSetNextLine,
	"shellexecute":       CmdShellExecute,
	"skk":                CmdSkk,
	"stat":               CmdStat,
	"utoa":               CmdUtoA,
	"which":              CmdWhich,
}
