package dos

const FILE_ATTRIBUTE_NORMAL = 128
const FILE_ATTRIBUTE_REPARSE_POINT = 1024
const FILE_ATTRIBUTE_HIDDEN = 2
const FILE_ATTRIBUTE_READONLY = 1
const FILE_ATTRIBUTE_SYSTEM = 4
const FILE_ATTRIBUTE_ARCHIVE = 32
const CP_THREAD_ACP = 3
const MOVEFILE_REPLACE_EXISTING = 1
const MOVEFILE_COPY_ALLOWED = 2
const MOVEFILE_WRITE_THROUGH = 8
const SW_HIDE = 0
const SW_MAXIMIZE = 3
const SW_MINIMIZE = 6
const SW_RESTORE = 9
const SW_SHOW = 5
const SW_SHOWDEFAULT = 10
const SW_SHOWMAXIMIZED = 3
const SW_SHOWMINIMIZED = 2
const SW_SHOWMINNOACTIVE = 7
const SW_SHOWNA = 8
const SW_SHOWNOACTIVATE = 4
const SW_SHOWNORMAL = 1
const COINIT_APARTMENTTHREADED = uintptr(2)
const COINIT_MULTITHREADED = uintptr(0)
const COINIT_DISABLE_OLE1DDE = uintptr(4)
const COINIT_SPEED_OVER_MEMORY = uintptr(8)
