package dos

const CP_THREAD_ACP = 3
const RESOURCE_CONNECTED = 1
const RESOURCE_CONTEXT = 5
const RESOURCE_GLOBALNET = 2
const RESOURCE_REMEMBERED = 3
const RESOURCETYPE_ANY = 0
const RESOURCETYPE_DISK = 1
const RESOURCETYPE_PRINT = 2
const RESOURCEDISPLAYTYPE_NETWORK = 6
const RESOURCEUSAGE_CONNECTABLE = 1
const RESOURCEUSAGE_CONTAINER = 2
const RESOURCEUSAGE_ATTACHED = 16
const RESOURCEUSAGE_ALL = 19
const ERROR_NOT_CONTAINER = 1207
const ERROR_INVALID_PARAMETER = 87
const ERROR_NO_NETWORK = 1222
const ERROR_EXTENDED_ERROR = 1208
const ERROR_NO_MORE_ITEMS = 259
const ERROR_MORE_DATA = 234
