go-importconst dos ^
    FILE_ATTRIBUTE_NORMAL ^
    FILE_ATTRIBUTE_REPARSE_POINT ^
    FILE_ATTRIBUTE_HIDDEN ^
    FILE_ATTRIBUTE_READONLY ^
    FILE_ATTRIBUTE_SYSTEM ^
    FILE_ATTRIBUTE_ARCHIVE ^
    CP_THREAD_ACP ^
    MOVEFILE_REPLACE_EXISTING ^
    MOVEFILE_COPY_ALLOWED ^
    MOVEFILE_WRITE_THROUGH ^
    SW_HIDE ^
    SW_MAXIMIZE ^
    SW_MINIMIZE ^
    SW_RESTORE ^
    SW_SHOW ^
    SW_SHOWDEFAULT ^
    SW_SHOWMAXIMIZED ^
    SW_SHOWMINIMIZED ^
    SW_SHOWMINNOACTIVE ^
    SW_SHOWNA ^
    SW_SHOWNOACTIVATE ^
    SW_SHOWNORMAL ^
    COINIT_APARTMENTTHREADED:uintptr ^
    COINIT_MULTITHREADED:uintptr ^
    COINIT_DISABLE_OLE1DDE:uintptr ^
    COINIT_SPEED_OVER_MEMORY:uintptr ^
    DRIVE_UNKNOWN ^
    DRIVE_NO_ROOT_DIR ^
    DRIVE_REMOVABLE ^
    DRIVE_FIXED ^
    DRIVE_REMOTE ^
    DRIVE_CDROM ^
    DRIVE_RAMDISK
@echo off
rem go-importconst -> https://github.com/zetamatta/go-importconst
